name: 6-1-1-CI-lint-test

on:
  push:
    branches: [dev, masterrr]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [??]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint
        uses: azohra/shell-linter@latest
        with:
          path: "setup.sh,scripts"

      - name: Run tests
        run: echo "Run tests"
