name: 6-1Hello-World

on: [pull_request]
#one: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Hello stage
        run: echo "hello world"
