name: 6-2-1-oidc-terraform

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::623152967016:role/oidc-Role-cvLK9cI4WdO5
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: run sts
        run: |
          aws sts get-caller-identity

      - name: Terraform Apply
        id: apply
        # env:
        # TF_VAR_ec2_name:  "${{ github.event.inputs.ec2-name }}"
        run: |
          TF_VAR_role_arn: "arn:aws:iam::623152967016:role/oidc-Role-cvLK9cI4WdO5"
          TF_VAR_region: "us-east-1"
          cd tf-example/
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve
