name: 6-2-CI-lint-test

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 21.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}"
      - name: Lint
        uses: azohra/shell-linter@latest
        with:
          path: "setup.sh,scripts"

      - name: Run tests
        run: npm test
